#include "UART.h"
#include "stm32f10x.h"
#include "LCD.h"
void UART_Init(void)
{

	RCC->APB2ENR |= RCC_APB2ENR_USART1EN | RCC_APB2ENR_IOPAEN;

	//UART1 TX(PA9)  RX(PA10)

	GPIOA->CRH &= ~(GPIO_CRH_MODE9 | GPIO_CRH_MODE10);
	GPIOA->CRH |= GPIO_CRH_MODE9;
	GPIOA->CRH &= ~GPIO_CRH_MODE10;

	GPIOA->CRH &= ~(GPIO_CRH_CNF9 | GPIO_CRH_CNF10);
	GPIOA->CRH |= GPIO_CRH_CNF9_1 | GPIO_CRH_CNF10_0;


	//0x1D4C 9600;
	USART1->BRR = 0x270;
	USART1->CR1 = USART_CR1_TE | USART_CR1_RE | USART_CR1_RXNEIE ;
	USART1->CR1 |= USART_CR1_UE;


	NVIC_EnableIRQ (USART1_IRQn);
}

